katzer/cordova-plugin-local-notifications

src/ios/APPLocalNotificationOptions.m
The interval string “hour” had a typo: “houre”.
=> Fixed interval constant "hour"

README.md
Documentation currently says that on Android only notification ID's must be convertible to a number. However, and I found this out the hard way, the code does not reflect this.
[`local-notification.js`](https://github.com/katzer/cordova-plugin-local-notifications/blob/7f6c1ce01e3041e16c61a94f4759c0455629705e/www/local-notification.js#L650-L652), approx line 650: 
options.id         = options.id.toString();
// ...
if (isNaN(options.id)) {
options.id = this.getDefaults().id;
}
Will convert any number string to `0`. This, combined with "Scheduling a local notification will override an earlier one with the same ID" leads to some very expected behaviour. If you're setting multiple notifications with non-numerical IDs, they'll end up being reset to 0 and just overwriting each other.
I would …
=> Warn against notification IDs that arent numbers

src/android/LocalNotification.java
In Android the ‘schedule’ event was not raised after scheduling one or
more tasks.
=> Fixed the schedule event

scripts/ios/didRegisterUserNotificationSettings.js
Updated the post-install script for iOS to look for the platforms module
in its new location. It'll look in the previous location too, so the
plugin should work on previous versions of Cordova too.
Fix for issue #531.
=> Updated the location for Cordova's platforms module

plugin.xml
The id of android v4 support library has changed from "android.support.v4" to "cordova-plugin-android-support-v4".
=> Updating id of android v4 support lib to latest

plugin.xml
Changing android-support dependency declaration to be compatible with other plugins like phonegap-plugin-push and cordova-plugin-facebook4. Issue katzer/cordova-plugin-local-notifications#632
=> Fix compatibility w/ other plugins due to android-support-v4.jar

src/android/notification/Manager.java
In previous old versions of the plugin, we were able to use non-integer values as notification keys (eg ms timestamp, which is a `long`). This isn't possible now, but a `NumberFormatException` exception is thrown when trying to add these to a list of `Integers`.
=> Catch previously-valid notification non-int keys.

www/local-notification.js
removed unused ‘scope’ variable from un function.
=> fixed reference error when calling un function

src/android/notification/Options.java
* assets.parse expects prefix of res://, file://, or http://.
=> Prepend default icon with missing prefix

src/ios/APPLocalNotificationOptions.m
Fix intervals for repeatable notifications.
Based on https://stackoverflow.com/a/40852161/506954 
Not sure what should be under seconds, but I am not even sure that the `every seconds` option should be available for notifications.
Right now notifications behaves as expected first and all next runs, while the before's solution worked unexpectedly.
=> Fix intervals for repeatable notifications on ios10

src/ios/APPLocalNotification.m
This solution will solve two plugins from disabling the other as a notification delegate in iOS. The current delegate set on the notification center is saved in a property. When presenting or handing response the handler checks the notification type as already present in the current code. If the notification type is a remote notification it is proxied to the previously available delegate.
This solves a current problem with the cordova-plugin-firebase:
1. Firebase registers as delegate
2. Local notifications registers as delegate
3. Remote push is received, is handled by local notifications and then returned without action.
And adds:
4. Local notifications calls Firebase's delegate and Firebase handles the remote notification as if it was the current delegate set on the notification …
=> Save delegate and proxy calls to previous delegate

www/local-notification.js
the option `timeoutAfter` currently does not work:
when parsing/evaluating options, the JS handler must use and set property `timeoutAfter ` instead of property `timeout` (which it currently does)
=> FIX option parsing for timeoutAfter

src/android/notification/Options.java, src/android/notification/util/AssetUtil.java
Fix issue https://github.com/katzer/cordova-plugin-local-notifications/issues/1786 if no smallIcon is set in the notification.
Prevent app crash in android oreo (8.1) tested also on 6.0 physical devices.
=> oreo bug fix, no smallIcon set in notification

www/local-notification.js
iOS getAll() terminates due to uncaught exception as reported in katzer#1657, fixed by correcting the _exec() function not to skip just falsy values.
=> Fixed JS _exec() wrapper not properly sending argument value 0

README.md, src/android/notification/Builder.java, src/android/notification/Options.java, www/local-notification.js
We use the plugin phonegap-push-plugin to receive push notifications when the app is in background. When the app is in foreground, we use this plugin to display a local notification that looks like the push received in background.
The push plugin has an option to convert the icon to a circular bitmap. We've added this feature to this plugin so our notifications can look the same both in foreground and in background.
=> Support circular icons

plugin.xml, src/android/notification/Options.java, src/android/notification/util/AssetUtil.java
See https://github.com/katzer/cordova-plugin-local-notifications/issues/1664
=> Add namespace to provider authority to prevent crashes on Android.

src/android/notification/Builder.java, src/android/notification/Manager.java, src/android/notification/Options.java
Created ability to have multiple channels
generated dynamically for vibrate/sound configurations.
=> Added Android 8 Support for Sound and Vibrate properties.

README.md, plugin.xml, src/android/LocalNotification.java, src/android/notification/Builder.java, src/android/notification/Manager.java, src/android/notification/Notification.java, src/android/notification/Options.java, src/windows/LocalNotificationProxy.js, www/local-notification.js
_NOTE:  This request is dependent on 02832e9, which is in pull request #1696_
- Added alarmVolume and resetDelay parameters.
These let the caller specify the volume how long to stay at that
volume before resetting.
- Added requestDoNotDisturbPermissions and hasDoNotDisturbPermissions
These allow the caller to check and request permissions to
take the user out of silent (for an alarm volume config).  This
also enables vibration when the phone is on silent (otherwise
vibration and volume do not work on Android 8+).
=> Added ability to customize alarm volume in Android

src/android/build/localnotification.gradle
- Starting on Gradle 7.0 the compile method is removed.
- Trying to build an app making use of the compile method returns
the following: > Could not find method compile() for arguments...
- This change migrates compile instances in the Gradle config file
to use implementation instead
=> Migrate to Gradle implementation

src/android/build/localnotification.gradle
Reverts katzer/cordova-plugin-local-notifications#1979
This Plugin needs a fresh restart. The fork https://github.com/moodlemobile/cordova-plugin-local-notification contains all necessary changes to make this Plugin work again. From there, we can build up everything again.
=> Revert "Migrate to Gradle implementation"

src/android/build/localnotification.gradle
Reverts katzer/cordova-plugin-local-notifications#1973
This Plugin needs a fresh restart. The fork https://github.com/moodlemobile/cordova-plugin-local-notification contains all necessary changes to make this Plugin work again. From there, we can build up everything again.
=> Revert "Update localnotification.gradle"

README.md, src/android/notification/Builder.java, src/android/notification/Options.java, www/local-notification.js
I added onlyAlertOnce option and updated readme file
=> Only alert once option

src/android/notification/Manager.java
to prevent crash:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
...
at de.appplant.cordova.plugin.notification.Manager.getOptions(Manager.java:391)
```
=> (android) bugfix: catch any exceptions when attempting to get option
